### ISSUE TITLE
'wrong private key type' during json web token verification

### ISSUE THREAD

**Issue by maxogden** [browserify/browserify-sign#32]
https://gist.github.com/maxogden/62b7119909a93204c747633308a4d769

browserifying with this:

browserify -t brfs index.js -o bundle.js

I get `Uncaught Error: wrong private key type`

from the line `if (signType !== 'ecdsa') throw new Error('wrong private key type')`

The signType in my case is 'rsa'

**Comment by calvinmetcalf** [comment]
```js
  // Even though we are specifying "RSA" here, this works with ECDSA
    // keys as well.
    var signer = crypto.createSign('RSA-SHA' + bits);
    var sig = (signer.update(thing), signer.sign(privateKey, 'base64'));
    return base64url.fromBase64(sig);
```

this line in jwa would probably be the issue, apparently we are more strict then node is handlings it when RSA is specifically requested

**Comment by calvinmetcalf** [comment]
all right 'RSA-SHA224/RSA-SHA256/RSA-SHA384/RSA-SHA512' case sensitive does appear to work for node

**Comment by sasukepatel** [comment]
im getting same error when i am trying to browserify web-push module. is there any solution to this?

**Comment by calvinmetcalf** [comment]
I think I might have fixed this already?

**Comment by sasukepatel** [comment]
yes..it is working if i follow code from "elliptical-curve-rsa-sic" branch.

not sure if i can do that(new to GitHub). i couldn't find updated code in master branch.

Thanks.

**Comment by calvinmetcalf** [comment]
ok merged and published that pull, had forgotten about it

**Comment by calvinmetcalf** [comment]
yes it should be, @JustinBeckwith you may need to debug a bit, my first guess is that you are using an older version or a different problem with the same error message
