### ISSUE TITLE
Expose algorithms

### ISSUE THREAD

**Issue by innovate-invent** [browserify/browserify-sign#55]
I am finding that the libraries that are attempting to use this are using different algorithm names than are listed in the algorithms.json. The one I am encountering now is `sha1` which I was able to get working by duplicating and renaming the existing `RSA-SHA1` algorithm. 

Ideally it would be great to export a method that allows adding custom algorithm definitions at runtime.

```js
// Very early in code
import { addAlgorithm } from 'broweserify-sign'
addAlgorithm('sha1', "rsa", "sha1", "3021300906052b0e03021a05000414")
```

**Comment by ljharb** [comment]
Making the package stateful seems like a very unwise idea.

Allowing you to supply an algorithm to use *in the call* might be nice, but since this package is mirroring node, node should add that ability before we do.
