### ISSUE TITLE
Incorrect dependency version. Please update

### ISSUE THREAD

**Issue by ttodua** [browserify/browserify-sign#62]
Browserify-sign module uses incorrect dependencies , as in our Vue-Cli project, the bundle ends up containing multiple `bn.js` files:
https://i.imgur.com/IQuwHHJ.png  (webpack-bundle-analyzer shows that).

So, another problem seems that (when you mouseover that bn.js) it is being created called from `MyProject/node_modules/browserify-sign/node_modules/bn.js/lib/bn.js`  while in the project there is already `MyProject/node_modules/bn.js/lib/bn.js` called once.

So, please correct that, so `B.S.` module wouldnt inject odd duplicated files into bundle, and used the available bn.js from project.

I doubt that it might be coming from this : https://github.com/crypto-browserify/browserify-rsa (as we use this module in our project too), but the `browserify-rsa` package.json depend son `bn.js : ^4.1` . So, could that be reason? if so, please update bn.js version for  `browserify-rsa` . Moreover, seems somoene had suggested that already - https://github.com/crypto-browserify/browserify-rsa/pull/13 but one year passed, no response.

**Comment by ljharb** [comment]
Yes, we use v5 here, so browserify-rsa is what needs the update.
