### ISSUE TITLE
elliptic version 6.5.3 has a vulnerability

### ISSUE THREAD

**Issue by samtjo** [browserify/browserify-sign#67]
Running an `npm audit` will show that `elliptic@6.5.3` has a moderate vulnerability - `Use of a Broken or Risky Cryptographic Algorithm`

![image](https://user-images.githubusercontent.com/14963680/110356543-489e8300-8032-11eb-9708-e430f3624067.png)

Upgrading elliptic to version `6.5.4` will resolve the vulnerability

**Comment by ljharb** [comment]
We depend on elliptic with a semver range, so nothing needs to be done except you updating your lockfile.
