### ISSUE TITLE
Fix for dsaVerify Security issue?

### ISSUE THREAD

**Issue by JESii** [browserify/browserify-sign#83]
Are there any plans to fix the Security issue GHSA-x9w5-v3q2-3rhw reported here? 
Dependabot is recommending an upgrade but there's no fix that I can see.
Thank you.

**Comment by ljharb** [comment]
That link specifically says v4.2.2 fixes it, which was released 4 months ago. The CVE link on NVD even links to https://github.com/browserify/browserify-sign/commit/85994cd6348b50f2fd1b73c54e20881416f44a30.

Duplicate of #81.
