### ISSUE TITLE
process is not defind

### ISSUE THREAD

**Issue by Elben9** [browserify/browserify-sign#85]
My project uses vue2 + webpack 5, and I have configured the fallback in webpack's resolve
```
resolve: {
    fallback: {
        crypto: require.resolve('crypto-browserify')
    }
}
```
crypto-browserify dependence browserify-sign

However, after upgrading the version of browserify-sign to 4.2.3, my project throws an error stating "process is not defined." 

How can I solve this problem? Thanks in advance.

**Comment by ljharb** [comment]
The general solution for webpack 5 is described in [this blog post](https://web.archive.org/web/20210309035442/https://blog.sindresorhus.com/webpack-5-headache-b6ac24973bf1?gi=a39eaf6f92ff) (unfortunately you may have to disable javascript to properly load that URL) - basically, restore the proper webpack 4 behavior of automatically polyfilling node globals and core modules.

Use https://github.com/Richienb/node-polyfill-webpack-plugin to do this.
