### ISSUE TITLE
process undefined in react native environment

### ISSUE THREAD

**Issue by adrianofoschi** [browserify/browserify-sign#86]
Hi, crypto-browserify uses this package and many react-native crypto apps use crypto-browserify.

Seems that the latest readable-stream downgrade in your package.json broken all this apps because process is not available.

In my case react native quick crypto.
Check this

https://github.com/margelo/react-native-quick-crypto/issues/242#issuecomment-1981784802

Any workaround?

**Comment by ljharb** [comment]
(A workaround is to declare a `process` global as an empty object, but it should really be fixed by default in metro)

**Comment by adrianofoschi** [comment]
> (A workaround is to declare a `process` global as an empty object, but it should really be fixed by default in metro)

Already tried it without success.

**Comment by ljharb** [comment]
I'm empathatic to this breaking, to be clear. readable-stream v2 was never in v4 of this package, v3 was added in v4.1.0.

https://stackoverflow.com/a/42439338/632724 suggests that metro *does* handle this properly, altho that was back in 2017. The next answer, https://stackoverflow.com/questions/42437995/react-native-process-env-has-only-node-env, suggests using babel - which could transform `process.browser` into `true`. Would that work?

**Comment by adrianofoschi** [comment]
> I'm empathatic to this breaking, to be clear. readable-stream v2 was never in v4 of this package, v3 was added in v4.1.0.

Yes it is what I meant. It works for me in v4.2.1 of this package. I see in your latest commit you downgrade readable-stream to v2 add added hash-base.

> https://stackoverflow.com/a/42439338/632724 suggests that metro _does_ handle this properly, altho that was back in 2017. The next answer, https://stackoverflow.com/questions/42437995/react-native-process-env-has-only-node-env, suggests using babel - which could transform `process.browser` into `true`. Would that work?

I will try one of these solutions. Thanks.

**Comment by ValenberghsSven** [comment]
We are having the same issue in an Emberjs environment
"process is not defined"

Traced it back to the latest patch of this repo
https://github.com/browserify/browserify-sign/compare/v4.2.2...v4.2.3#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R40

Found the exact line that is throwing the error in `readable-stream` when comparing both versions
https://github.com/nodejs/readable-stream/compare/v2.3.8...v3.6.2#diff-974ee391a6c413410bd53dd05ab5d0672c326587ba3a270c918168de594a75ddL146


We managed to fix it by adding `process: 'process/browser.js',` to our configuration

**Comment by ljharb** [comment]
Without exception, your bundler is broken if this doesn't work by default, but I'm glad to hear that ember has a simple config to fix it.

**Comment by ljharb** [comment]
@akshayOodlesTech does your webpack config apply that plugin to node_modules code? if so, then i'd file an issue with webpack.

**Comment by rjblopes** [comment]
My comment on [commit](https://github.com/browserify/browserify-sign/commit/9e2bf122b70970cb92f69d53e963f18299f14d66#commitcomment-139724243) relates to this issue.

**Comment by printfn** [comment]
I’m getting this issue with Vite. For now I’ve worked around it by adding this entry to the `define` section in my vite.config.ts:

```typescript
export default defineConfig(env => ({
    define: {
        ...(process.env.VITEST ? {} : { 'process.version': JSON.stringify(process.version) }),
    },
}));

**Comment by ljharb** [comment]
To be clear, that’s not a workaround, that’s the proper fix for vite.

**Comment by shamilovtim** [comment]
@calvinmetcalf Are you aware of what @ljharb is doing here with your project? This is user hostile. He shipped a breaking change in patch release not out of maintenance but out of a personal agenda to support ancient node versions and he's refusing to roll it back. This is not being a maintainer, this is a hostile takeover.

**Comment by ljharb** [comment]
@shamilovtim the breaking change was dropping support for those node versions in the first place. if metro can’t properly bundle node modules, then it shouldn’t have ever worked in the first place.

**Comment by ljharb** [comment]
Since using newer versions of readable-stream would be a breaking change, and the usage of `process` is inside `readable-stream` v3, it's not something that can (or should) be fixed here.

Solutions include 1) using a non-broken bundler, 2) configuring your broken bundler to ensure `process` is an object that always exists, or 3) get a readable-stream v3 backport patch published that doesn't assume the existence of `process`.
