### ISSUE TITLE
breaking changes in 4.2.3

### ISSUE THREAD

**Issue by shamilovtim** [browserify/browserify-sign#88]
- `crypto-browserify` depends on this package transitively
- this package shipped a breaking change in 4.2.3 by supporting node v1's APIs which modern projects don't support

please ship a major semver release for the 4.2.3 change and push a 4.2.4 that reverts the changes in 4.2.3.

**Comment by ljharb** [comment]
Can you elaborate on the "breaking change"?

**Comment by shamilovtim** [comment]
> Can you elaborate on the "breaking change"?

There was a change made to intentionally support **node v1** and this was transitively shipped into users projects. This was labeled as a patch release. We don't support node v1 nor do we intend to. This should not be a patch release.

**Comment by shamilovtim** [comment]
Runtime crash is `TypeError: Cannot read property 'slice' of undefined`. We are pinning to `4.2.2` for now but cannot do that for downstream consumers of packages so a revert is needed here.

**Comment by ljharb** [comment]
This is a node module; process always exists. The issue is that you’re using a bundler that is broken, and fails to provide process.env.

**Comment by shamilovtim** [comment]
> This is a node module; process always exists. The issue is that you’re using a bundler that is broken, and fails to provide process.env.

It worked before the patch release. The issue is that the published patch release to widen support to an ancient version of node broke modern node. Like many others I'm not interested in doing the labor to support that. Our users are on node 18+.

**Comment by ljharb** [comment]
The breaking change was _dropping_ older node versions; the fix was to restore them.

This has nothing to do with supporting old node versions, really - it's that metro is not properly bundling node modules by providing/shimming `process`. The only fix needed is to your RN build.

**Comment by shamilovtim** [comment]
@ljharb The fix is clearly to remove or hard fork whatever you're maintaining since you lack judgement and respect for people's time. Toward that end I'm pulling `crypto-browserify` out of a dep and will be sure to audit the rest of our supply chain for these kinds of shenanigans since it's clear to me that you're doing this stuff as some sort of crusade.

**Comment by ljharb** [comment]
@shamilovtim "going out of your way to remove a specific package" seems like a crusade to me :-)

I have plenty of respect for people's time - the amount of time wasted by bundlers failing to properly handle node builtins is massive, and tacitly endorsing it isn't helping anyone.
