### ISSUE TITLE
Fix for elliptic package SNYK Vulerability

### ISSUE THREAD

**Issue by PrithvirajTK** [browserify/browserify-sign#89]
Can we expect this vulnerability fixed?
https://security.snyk.io/package/npm/elliptic

**Comment by ljharb** [comment]
That's not this package.

**Comment by mlhDevelopment** [comment]
For reference, see also [issue 95](https://github.com/browserify/browserify-sign/issues/95) and options listed there to mitigate vulnerability risk.
